# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!
pod 'AFNetworking', '~> 2.0'
pod 'SDWebImage', '~>3.7'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'YYModel'
pod 'YYCategories'
pod 'MJExtension'
pod 'MJRefresh'
pod 'Masonry'
target 'TSFrameLiteDemo' do

end

